name: Backup Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * */2 * *" # 每两天运行一次

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # 启用 LFS

      - name: Set timezone and current time
        run: |
          current_time=$(TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S")
          echo "current_time=${current_time}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y aria2 jq

      - name: Download and setup 7zip
        run: |
          mkdir -p Archive/7zip
          cd Archive/7zip
          wget "https://www.7-zip.org/a/7z2301-linux-x64.tar.xz" -O 7zip.tar.xz
          tar -xf 7zip.tar.xz
          mv 7zz ..
          cd ..
          rm -rf 7zip && chmod +x 7zz

      - name: Download v2rayN assets
        run: |
          mkdir -p Archive/v2rayn
          release_tag=$(curl -s https://api.github.com/repos/2dust/v2rayN/releases | jq -r ".[0].tag_name")
          cd Archive/v2rayn
          mkdir -p "Release_${release_tag}"
          cd "Release_${release_tag}"
          urls=$(curl -s https://api.github.com/repos/2dust/v2rayN/releases/latest | jq -r ".assets[] | .name + \"\n\" + .browser_download_url")
          echo "$urls" | while IFS= read -r item; do
            name=$(echo "$item" | head -n 1)
            url=$(echo "$item" | tail -n 1)
            wget -O "$name" -q "$url"
          done

      - name: Download v2rayNG assets
        run: |
          mkdir -p Archive/v2rayng
          release_tag=$(curl -s https://api.github.com/repos/2dust/v2rayNG/releases | jq -r ".[0].tag_name")
          cd Archive/v2rayng
          mkdir -p "Release_${release_tag}"
          cd "Release_${release_tag}"
          urls=$(curl -s https://api.github.com/repos/2dust/v2rayNG/releases/latest | jq -r ".assets[] | .name + \"\n\" + .browser_download_url")
          echo "$urls" | while IFS= read -r item; do
            name=$(echo "$item" | head -n 1)
            url=$(echo "$item" | tail -n 1)
            wget -O "$name" -q "$url"
          done

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Track large files with Git LFS
        env:
          current_time: ${{ env.current_time }}
        run: |
          git lfs track "*.zip"
          git lfs track "*.7z"
          git lfs track "*.apk"
          git add .gitattributes
          if git diff --cached --quiet; then
            echo "No changes in .gitattributes"
          else
            git commit -m "更新时间：${{ env.current_time }}"
          fi

      - name: Commit and push changes
        env:
          current_time: ${{ env.current_time }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Archive/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase origin main
            git stash pop
            git add Archive/
            git add .gitattributes
            git commit -m "更新时间：${{ env.current_time }}"
            git push origin main
          fi
